apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: accounts-prod

resources:
  - ../../base

patchesStrategicMerge:
  - ingress-ibm.yaml
  - postgresql-patch.yaml

images:
  - name: accounts
    newName: us.icr.io/accounts-namespace/accounts
    newTag: latest

secretGenerator:
  - name: app-secrets
    envs:
      - secret.env
    type: Opaque

replicas:
  - name: accounts
    count: 1
