apiVersion: v1
kind: Secret
metadata:
  name: docker-config
type: Opaque
stringData:
  config.json: |
    {"auths":{"us.icr.io":{"username":"iamapikey","password":"aLVAeQ2M9B6QsgVpEUaLd53r9ZxXvJsF6JwQVjnCL8wo","email":"maduemeka254@gmail.com","auth":"aWFtYXBpa2V5OmFMVkFlUTJNOUI2UXNnVnBFVWFMZDUzcjlaeFh2SnNGNkp3UVZqbkNMOHdv"}}}
