#
# This pipeline needs the following tasks from Tekton Catalog
#   - git-clone
#   - buildah
#
# Custom tasks defined in tasks.yaml:
#   - cleanup
#   - kubectl-deploy
#
# Custom tasks defined in flake8.yaml:
#   - flake8
#
# Custom tasks defined in nosetests.yaml:
#   - nosetests
#
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: cd-pipeline
spec:
  workspaces:
    - name: pipeline-workspace
    - name: docker-credentials
  params:
    - name: repo-url
    - name: branch
      default: main
    - name: image-tag
      default: "2"
  tasks:
    - name: init
      workspaces:
        - name: source
          workspace: pipeline-workspace
      taskRef:
        name: cleanup

    - name: clone
      workspaces:
        - name: output
          workspace: pipeline-workspace
      taskRef:
        name: git-clone
      params:
        - name: url
          value: $(params.repo-url)
        - name: revision
          value: $(params.branch)
      runAfter:
        - init

    - name: lint
      workspaces:
        - name: source
          workspace: pipeline-workspace
      taskRef:
        name: flake8
      params:
        - name: image
          value: python:3.9-slim
        - name: args
          value:
            - --count
            - --max-complexity=10
            - --max-line-length=127
            - --statistics
      runAfter:
        - clone

    - name: test
      workspaces:
        - name: source
          workspace: pipeline-workspace
      taskRef:
        name: nosetests
      params:
        - name: image
          value: python:3.9-slim
        - name: database-url
          value: postgresql://postgres:postgres@localhost:5432/testdb
        - name: requirements
          value: requirements.txt
      runAfter:
        - clone

    - name: build-image
      workspaces:
        - name: source
          workspace: pipeline-workspace
        - name: dockerconfig
          workspace: docker-credentials
      taskRef:
        name: buildah
      params:
        - name: IMAGE
          value: us.icr.io/accounts-namespace/accounts:$(params.image-tag)
        - name: DOCKERFILE
          value: ./Dockerfile
        - name: CONTEXT
          value: .
        - name: TLSVERIFY
          value: "false"
      runAfter:
        - lint
        - test

    - name: deploy
      workspaces:
        - name: source
          workspace: pipeline-workspace
      taskRef:
        name: kubectl-deploy
      params:
        - name: image-tag
          value: $(params.image-tag)
      runAfter:
        - build-image
