apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - ../../base

images:
  - name: accounts
    newName: us.icr.io/accounts-namespace/accounts
    newTag: "2"

secretGenerator:
  - name: app-secrets
    envs:
      - secret.env
    type: Opaque

patches:
  - patch: |-
      - op: add
        path: /spec/template/spec/imagePullSecrets
        value:
          - name: icr-secret
    target:
      kind: Deployment
      name: accounts
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
    target:
      kind: Deployment
      name: accounts
  - patch: |-
      - op: add
        path: /spec/template/spec/affinity
        value:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 100
                podAffinityTerm:
                  labelSelector:
                    matchExpressions:
                      - key: app
                        operator: In
                        values:
                          - accounts
                  topologyKey: kubernetes.io/hostname
    target:
      kind: Deployment
      name: accounts
