apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

labels:
  - pairs:
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/part-of: accounts-api

resources:
  - deployment.yaml
  - service.yaml
  - postgresql.yaml
  - postgresql-pvc.yaml
  - ingress.yaml
